#!/bin/zsh

function _fuzzy-fs-list-recent-dir {
    local field=list-rencent-dir
    local res
    # if you use z to jump between directories
    if {which _z &> /dev/null}; then
        res=$(_z -l 2>&1 | tac | awk '{for(i=2; i<=NF; ++i) printf "%s ", $i; print ""}' | sed "s/^/$recent_dir_icon /")
    fi
    # if you use autojump
    if {which autojump &> /dev/null}; then
        res=$(autojump -s | sed -E '/^___/q;s/[0-9]*\.[0-9]*:[[:space:]]*//;' | head -n-1 | sed "s/^/$recent_dir_icon /")
    fi
    fzf_items+=("${(f)res}")
}
