#!/bin/zsh

function _fuzzy-fs-list-ancestors {
    local filename=$PWD
    local relative=..
    while [[ $filename != / ]]; do
        filename=$(dirname $filename)
        fzf_items+=("$ancestor_icon $relative \t $filename")
        relative=$relative.
    done
}
