#!/bin/zsh

zparseopts -no-color=no_color \
           a=show_hidden \
           d=debug_mode
[[ -z "$no_color" ]] && color_param=--color=always

if {which bat &> /dev/null}; then
    less_command="bat -p $color_param"
elif {which less &> /dev/null}; then
    less_command="less"
else
    less_command="more"
fi

filename=$argv[$ARGC]
if [[ -d "$filename" ]]; then
    echo "$(basename $filename)" is a directory:
    echo
    if type exa &> /dev/null; then
        exa -la $color_param "$filename"
    else
        ls -la $color_param "$filename"
    fi
elif [[ -f "$filename" ]]; then
    ${=less_command} "$filename"
fi
