#!/bin/zsh

if [[ -z "$no_color" ]]; then
    color_param=--color=always
else
    color_param=--color=never
fi

target=$($base_dir/function/_ffs-parse-item $*)
notify-send target '"'$target'"'
[[ -d "$target" ]]
notify-send good $?

if [[ -d "$target" ]]; then
    notify-send dir-target $target
    echo "$target" is a directory:
    echo
    if [[ "$ls_command" = exa ]]; then
        exa -la $color_param "$target"
    else
        ls -la $color_param "$target"
    fi
elif [[ -f "$target" ]]; then
    notify-send file-target $target
    ${=pager_command} "$target"
fi
