#!/bin/zsh

if [[ -z "$no_color" ]]; then
    color_param=--color=always
else
    color_param=--color=never
fi

target=$($base_dir/function/_ffs-parse-item $*)
[[ -d "$target" ]]

if [[ -d "$target" ]]; then
    echo "$target" is a directory:
    echo
    if [[ "$ls_command" = exa ]]; then
        exa -la $color_param "$target"
    else
        ls -la $color_param "$target"
    fi
elif [[ -f "$target" ]]; then
    case "$target" in
        *.pdf)
            pdftotext "$target" - | ${=pager_command}
            ;;
        *)
            ${=pager_command} "$target"
            ;
    esac
fi
