#!/bin/zsh

# for debug
export field=ls-panel
autoload -Uz debug_var

# key bindings
key_enter=${key_enter:-enter}
key_delete=${key_delete:-ctrl-d}
key_exit=${key_exit:-ctrl-c}
key_parent=${key_parent:-ctrl-u}
key_edit=${key_edit:-ctrl-e}
key_run=${key_run:-ctrl-r}
key_command=${key_command:-ctrl-t}

# parameters and settings
current_dir="$*"
[[ $enable_color == true ]] && color_param=--ansi

# get header
header="Directory: $current_dir"$'\n'
header=$header$'\n'"Open: $key_enter"$'\t'"Delete: $key_delete"$'\t'"Edit: $key_edit"
header=$header$'\n'"Exit: $key_exit"$'\t'"Go parent: $key_parent"$'\t'"Run: $key_run"
header=$header$'\n'"Run External Command: $key_command"
header+=$'\n'" "

# show fzf and get result
res=$(
    ${=ls_command} $current_dir | \
        fzf --prompt="Filter: " \
            --header="$header" \
            --print-query \
            $color_param \
            --preview="$preview_command $current_dir/{-1}" \
            --expect "$key_enter,$key_delete,$key_exit,$key_parent,$key_edit,$key_run,$key_command"
)

debug_var res

# if fzf returned successfully, return
if [[ $? = 0 ]] {
       query=$(echo $res | head -n1)
       key=$(echo $res | head -n2 | tail -n1)
       item=$(echo $res | tail -n+3)
       debug_var key
       debug_var item
       echo $query
       case "$key" in
           $key_enter)
               echo cd
               filename=$current_dir/$(echo $item | awk '{print $NF}')
               echo $filename
               ;;
           $key_parent)
               echo cd
               echo $(dirname $current_dir)
               ;;
           $key_delete)
               echo rm
               filename=$current_dir/$(echo $item | awk '{print $NF}')
               echo $filename
               ;;
           $key_edit)
               echo edit
               filename=$current_dir/$(echo $item | awk '{print $NF}')
               echo $filename
               ;;
           $key_run)
               echo run
               filename=$current_dir/$(echo $item | awk '{print $NF}')
               echo $filename
               ;;
           $key_command)
               echo external_command
               filename=$current_dir/$(echo $item | awk '{print $NF}')
               echo $filename
               ;;
           $key_exit)
               echo exit
               ;;
       esac
   } else {
# else return exception
       echo exception
   }
