#!/bin/zsh

[[ $enable_color == true ]] && color_param=--color=always

if {which bat &> /dev/null} {
       less_command="bat $color_param"
   } elif {which less &> /dev/null} {
       less_command="less"
   } else {
       less_command="more"
   }

filename="$*"
if [[ -d "$filename" ]] {
       echo "$(basename $filename)" is a directory:
       echo
       ls --color=always "$filename"
   } elif [[ -f "$filename" ]] {
       ${=less_command} "$filename"
   }
