#!/bin/zsh

function _fuzzy-fs-edit {
    local field=edit
    local pwd=$1
    local target=$2
    if [[ -z $TMUX ]]; then
        $EDITOR $target
    else
        tmux new-window -c "$pwd" -n "edit $(basename $target)" "$EDITOR" "$target"
    fi
}
