#!/bin/zsh

function _fuzzy-fs-open-shell {
    local pwd=$*
    if [[ ! -z $TMUX ]]; then
        tmux new-window -c "$pwd" -n "dir $(basename $pwd)"
    elif type "$ffs_terminal" &> /dev/null; then
        ${=terminal_command} $pwd &> /dev/null &
        disown
    else
        $ffs_shell
    fi
}
