#!/bin/zsh

function open-shell {
    local pwd=$*
    if [[ ! -z $TMUX ]]; then
        tmux new-window -c "$pwd" -n "dir $(basename $pwd)"
    elif {which "$TERMINAL" &> /dev/null}; then
        $TERMINAL --workdir $pwd
    else
        $SHELL
    fi
}
