#!/bin/zsh

function open-shell () {
    local pwd=$*
    if [[ ! -z $TMUX ]] {
        tmux new-window -c "$pwd" -n "dir $(basename $pwd)"
    } elif {which "$TERMINAL" &> /dev/null} {
        $TERMINAL --workdir $pwd
    } else {
        $SHELL
    }
}
