#!/bin/zsh

function _fuzzy-fs-parse-file-item {
    # for debug
    local field=parse-file-item

    # strip off color
    local item=$(echo $* | sed $'s/\e\\[[0-9;:]*[a-zA-Z]//g')

    # find the target column
    local i=0
    local cur_column=1
    local ch prech
    while [[ $cur_column != $filename_column ]]; do
        ch=$item[$((++i))]
        if [[ "$ch" != ' ' && "$prech" == ' ' ]]; then
            cur_column=$((cur_column+1))
        fi
        prech=$ch
    done

    # if the file is not a link, the file name spans from the target column to the end
    local target=$item[$i,-1]
    # otherwise remove anything after the " -> " sign
    if [[ $item[1] == l ]]; then
        target=$(echo "$target" | grep -o ".* -> ")
        target=$target[1,-5]
    fi

    _fuzzy-fs-debug-var item
    _fuzzy-fs-debug-var target
    echo $target
}
