#!/bin/zsh

function _fuzzy-fs-list-file {
    # for debug
    local field=list-file
    _fuzzy-fs-debug-var ls_command

    local params=""
    local start_line=""
    local color_param=""
    local shown_hidden=""
    case $ls_command in
        exa)
            params="-lh --git"
            start_line=2
            [[ ! -z "$show_hidden" ]] && local hidden_param=-a
            ;;
        ls)
            params="-lh"
            start_line=2
            [[ ! -z "$show_hidden" ]] && local hidden_param=-A
            ;;
    esac

    if [[ -z "$no_color" ]]; then
        color_param=--color=always
    else
        color_param=--color=never
    fi

    _fuzzy-fs-debug-var params
    _fuzzy-fs-debug-var color_param
    _fuzzy-fs-debug-var hidden_param
    _fuzzy-fs-debug-var start_line

    local ls_res=$($ls_command ${=params} $color_param $hidden_param)
    ls_res=("${(f@)ls_res}")
    local header=$ls_res[1]
    local items=($ls_res[$start_line,-1])

    # count the column number to know which column is filename
    case $ls_command in
        exa) filename_column=$(($(echo $header | wc -w)+1)) ;;
        ls) filename_column=9 ;;
    esac

    _fuzzy-fs-debug-var filename_column

    # TODO: don't do sed repeatly
    for line in $items; do
        uncolored_line=$(echo $line | sed $'s/\e\\[[0-9;:]*[a-zA-Z]//g')
        case $uncolored_line[1] in
            d) res+=("$directory_icon $line") ;;
            l) res+=("$link_icon $line") ;;
            *) res+=("$file_icon $line") ;;
        esac
    done

}
