#!/bin/zsh

function _fuzzy-fs-parse-file-item {
    # for debug
    local field=parse-file-item

    # strip off color
    local item=$(echo $* | sed $'s/\e\\[[0-9;:]*[a-zA-Z]//g')
    local target=$(echo $item | awk '{print $'$filename_column'}')

    _fuzzy-fs-debug-var item
    _fuzzy-fs-debug-var target
    echo $target
}
