#!/bin/zsh

export field=_history

HISTORY_BASE=/home/qmxue/.directory_history

debug $HISTFILE
debug $HISTORY_BASE

# if you are using per-directory-history, please set $HISTORY_BASE
if [[ ! -z "$HISTORY_BASE" ]] {
    _per_directory_history_directory="$HISTORY_BASE${PWD:A}/history"
    mkdir -p ${_per_directory_history_directory:h}

    #read history in new file
    if [[ -e $_per_directory_history_directory ]]; then
        fc -R $_per_directory_history_directory
    fi
}

history | sed -re 's/^\s*[0-9]+\s*//'
