#!/bin/zsh

export field=_history
autoload -Uz debug_var

HISTORY_BASE=/home/qmxue/.directory_history

debug_var $HISTFILE
debug_var $HISTORY_BASE

current_path="$*"
# if you are using per-directory-history, please set $HISTORY_BASE
if [[ ! -z "$HISTORY_BASE" ]] {
    _per_directory_history_directory="$HISTORY_BASE${current_path:A}/history"
    mkdir -p ${_per_directory_history_directory:h}

    #read history in new file
    if [[ -e $_per_directory_history_directory ]]; then
        fc -R $_per_directory_history_directory
    fi
}

history | sed -re 's/^\s*[0-9]+\s*//' | awk '!x[$0]++' | sed 's/^/Command:  /'
