#!/bin/zsh

function add-recent-dir {
    dir="$*"
    _z_data=${_Z_DATA:-$HOME/.z}
    if [[ -f $_z_data ]] {
        _z --add $dir
    }
    if {which autojump &> /dev/null} {
        autojump --add $dir
    }
}
