#!/bin/zsh

function find-recursively {
    field=find-recursively
    # params
    [[ -z "$no_color" ]] && color_param=--color=always

    current_path="$*"
    debug_var current_path

    if {which fd &> /dev/null} {
        if [[ -z "$show_hidden" ]] {
            fd $color_param -I . "$current_path"
        } else {
            fd $color_param -IH . "$current_path"
        }
    } else {
        if [[ -z "$show_hidden" ]] {
            find "$current_path" -not -path '*/\.*'
        } else {
            find "$current_path"
        }
    }
}
