#!/bin/zsh

function list-ancestors {
    local filename=$*
    local relative=..
    while [[ $filename != / ]]; do
        filename=$(dirname $filename)
        echo $ancestor_icon"  "$relative$'\t'$filename
        relative=$relative.
    done
}
