#!/bin/zsh

function list-recent-dir {
    local field=list-rencent-dir
    debug_var recent_dir_icon
    # if you use z to jump between directories
    if [[ -f $HOME/.z ]] {
           cat $HOME/.z | sed "s/^/$recent_dir_icon  /;s/|[0-9]\+|[0-9]\+$//"
    }
}
