#!/bin/zsh

function open-shell () {
    local current_path=$*
    if [[ ! -z $TMUX ]] {
        tmux new-window -c "$current_path" -n "dir $(basename $current_path)"
    } elif {which "$TERMINAL" &> /dev/null} {
        $TERMINAL --workdir $current_path
    } else {
        $SHELL
    }
}
