#!/bin/zsh

function _fuzzy-fs-first-available-command {
    for candidate in $argv; do
        cmd=$(echo $candidate | awk '{print $1}')
        if type "$cmd" > /dev/null; then
            echo $candidate
            return 0
        fi
    done
    return 1
}
