#!/bin/zsh

function _fuzzy-fs-find-recursively {
    local field=find-recursively
    # params
    [[ -z "$no_color" ]] && color_param=--color=always

    if type fd &> /dev/null; then
        if [[ -z "$show_hidden" ]]; then
            fd $color_param -I . "$PWD"
        else
            fd $color_param -IH . "$PWD"
        fi
    else
        if [[ -z "$show_hidden" ]]; then
            find "$PWD" -not -path '*/\.*'
        else
            find "$PWD"
        fi
    fi
}
