#!/bin/zsh

function find-recursively {
    local field=find-recursively
    # params
    [[ -z "$no_color" ]] && color_param=--color=always

    local pwd="$*"

    if {which fd &> /dev/null} {
        if [[ -z "$show_hidden" ]] {
            fd $color_param -I . "$pwd"
        } else {
            fd $color_param -IH . "$pwd"
        }
    } else {
        if [[ -z "$show_hidden" ]] {
            find "$pwd" -not -path '*/\.*'
        } else {
            find "$pwd"
        }
    }
}
