#!/bin/zsh

function find-recursively {
    local field=find-recursively
    # params
    [[ -z "$no_color" ]] && color_param=--color=always

    local pwd="$*"

    if {which fd &> /dev/null}; then
        if [[ -z "$show_hidden" ]]; then
            fd $color_param -I . "$pwd"
        else
            fd $color_param -IH . "$pwd"
        fi
    else
        if [[ -z "$show_hidden" ]]; then
            find "$pwd" -not -path '*/\.*'
        else
            find "$pwd"
        fi
    fi
}
